name: ChzzkRPG
version: '${project.version}'
main: com.chzzk.rpg.ChzzkRPG
api-version: '1.21'
authors: [ Antigravity ]
depend: [ Vault ]
softdepend: [ PlaceholderAPI, Multiverse-Core, WorldGuard ]

commands:
  rpg:
    description: Main RPG command
    usage: /rpg
  rpgadmin:
    description: Admin RPG command
    usage: /rpgadmin
  stats:
    description: Open Stats GUI
  job:
    description: Open Job GUI
  enhance:
    description: Open Enhance GUI
  builder:
    description: Toggle Builder Mode / Open Builder GUI
  land:
    description: Land Management
  contract:
    description: Contract Management
  repair:
    description: Repair items (Blacksmith)
  guild:
    description: Guild Management
  rtp:
    description: Random teleport

permissions:
  rpg.use:
    description: Default permission for players
    default: true
  rpg.land.guildclaim:
    description: Guild land claim permission
    default: op
  rpg.admin:
    description: Admin permission
    default: op
  rpg.builder:
    description: Builder permission
    default: op
  rpg.rtp:
    description: Random teleport permission
    default: true
